#!/bin/bash

set -euo pipefail

maxParallel=20

echo "parallelism,TimeTaken(virtual),TimeTaken(platform),TimeTaken(coroutine),#concurrent(virtual),#concurrent(platform),#concurrent(coroutine),#threads(virtual),#threads(platform),#threads(coroutine)"

for ((i = 1; i <= maxParallel; i++)); do
  java -jar build/libs/VirtualThreadsVsCoroutine-1.0.0.jar "$i"
done
