#!/bin/bash

set -euo pipefail

maxParallel=2

echo "parallelism,TimeTaken(virtual),TimeTaken(platform),#concurrent(virtual),#concurrent(platform),#threads(virtual),#threads(platform)"

for ((i = 1; i <= maxParallel; i++)); do
  java -jar build/libs/VirtualThreadsVsCoroutine-1.0.0.jar "$i"
done
